#!/bin/bash
set -e

cd $(dirname $0)/..

echo Running validation

PACKAGES="$(go list ./...)"

echo Running: go fmt
test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"

echo Running: hadolint for Dockerfile
hadolint package/Dockerfile

if ! command -v golangci-lint; then
    echo Skipping validation: no golangci-lint available
    exit
fi

echo Running: golangci-lint
golangci-lint run
